services:
  - type: web
    name: ggeutmalitgi
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: JWT_SECRET
        sync: false
      - key: KOREAN_DICT_API_KEY
        sync: false
